/**
 * Assemble demo/paph4x.html — the PAPH 4.1 evidence bench.
 *
 * The bench is a SINGLE file you can hand to anyone: no server, no network,
 * fonts included.  That property is worth keeping, but a hand-inlined engine
 * goes stale the moment the comparator moves, so the file is generated instead
 * of edited: this script inlines the CURRENT `src/paph3.cjs`, `src/paph4.cjs`
 * and `demo/cal-core.cjs` into the page.  Run `npm run build:bench` after any
 * engine change and the bench cannot silently disagree with the package.
 *
 * Sources live in demo/bench4x/ — brand CSS (the Pixagram design system),
 * the page body, and the bench application.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const src = join(root, 'demo', 'bench4x');
const read = (...p) => readFileSync(join(...p), 'utf8');

const brandCss = read(src, 'brand.css');       // @font-face payloads + design tokens
const appCss = read(src, 'bench.css');         // application layer, borderless system
const body = read(src, 'body.html');           // the nine sections
const app = read(src, 'bench.js');             // the bench application

const engines = [
  ['paph3 — the v3 wire engine (SPEC-003)', read(root, 'src', 'paph3.cjs')],
  ['paph4 — comparators 4 and 41 (SPEC-004, SPEC-004.1)', read(root, 'src', 'paph4.cjs')],
  ['cal-core — the calibration loop the bench shares with the suites', read(root, 'demo', 'cal-core.cjs')]
];

const out = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PAPH 4.1 — Evidence Bench</title>
<!-- Generated by tools/build-paph4x.mjs — edit demo/bench4x/*, not this file. -->
${brandCss}
${appCss}
</head>
${body}
${engines.map(([label, code]) => `<script>/* ${label} */\n${code}\n</script>`).join('\n')}
<script>${app}</script>
</body>
</html>
`;

const dest = join(root, 'demo', 'paph4x.html');
writeFileSync(dest, out);
const kb = (out.length / 1024).toFixed(0);
console.log(`demo/paph4x.html — ${kb} kB, engines inlined from src/ at build time`);
